@startuml

hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
'skinparam Padding 5
skinparam ParticipantPadding 15

skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class ConverterDefinitionDescription {
    displayName : string
    description : string
}

class ConverterDefinition  <<Pivot>> {
  description : ConverterDefinitionDescription  
  options : Array Of NamedOption  
  defaultOption : String
  baseOption : SingleOption
}

class NamedOption {
    option : String
    definition : SingleOption
}

class CharacteristicPropertyType <<Enumeration>> {
    list
    record
}

class CharacteristicProperty {
    parentProperty : String
    type : CharacteristicPropertyType
    propertyList : Array of String
    includeIndex : Boolean
}

together {
class CharacteristicProperty
class CharacteristicPropertyType
}

together  {
class FormatDefintion
class NamedFormat
class SingleFormat
}

class SingleFormat {
    objectFilter : Array of String
    iconColor : String
    skinParams : Array of String
    captionShowIdent : Boolean
    captionShowTitle : Boolean
    captionShowType : Boolean
    captionSplitCharacter:String
    captionSplitLength:Integer
    showAttributes : Boolean
    showCharacteristics : Boolean
    showFromRelations : Boolean
    showIfEmpty : Boolean
    showToRelations : Boolean
    valueSplitLength : Integer
}

class FormatDefintion {
    baseFormat : SingleFormat
    formats : Array of NamedFormat
}

class NamedFormat {
    format : String
    definition: SingleFormat
}

class PropertyValue {
    propertyName : String
    childPropertyName : String
    nextValueSeparator : String
}

class ObjectProperty {
    objectName : String
    generateWithoutIdentifier : Boolean
}
class SingleOption {
    continueAfterUnhandledObjects : Boolean
    groupDetailObjectsTogether : Boolean
    hideDuplicateRelations : Boolean
    identifyObjectsByTypeAndIdent : Boolean
    groupDetailObjectsTogether : Boolean
    hideDuplicateRelations : Boolean
    ---
    pumlHeaderLines : Array of String
    objectFormats : FormatDefinition
    ---
    legendShowInfo : Boolean
    legendShowObjectFormats : Boolean
    legendShowFileInfos : Boolean
    ---
	attributeProperties : Array of string
    objectProperties : Array of ObjectProperty
	objectTypeProperties : Array of PropertyValue
    objectTypeRenames : Array of String
    objectIdentifierProperties : Array of PropertyValue
	objectTitleProperties : Array of PropertyValue
    objectDetailProperties : Array of String
    relationshipProperties : Array of String
    relationshipTypeProperties : Array of PropertyValue
    relationshipTypeArrowFormats : Array of String
    groupProperties : Array of string
    characteristicProperties : Array of CharacteristicProperty
    hiddenProperties : Array of String
}

ConverterDefinition::options -down-> "0..*" NamedOption: "        "
ConverterDefinition::baseOption -right-> "0..1" SingleOption::option
ConverterDefinition::description -right-> "0..1" ConverterDefinitionDescription
NamedOption::definition --> "0..1" SingleOption
SingleOption::characteristicProperties --> "0..*" CharacteristicProperty::parentProperty
SingleOption::objectFormats --> "0..1" FormatDefintion
SingleOption::objectProperties --> "0..*" ObjectProperty
SingleOption::objectIdentifierProperties -right-> "0..*" PropertyValue
SingleOption::objectTitleProperties --> "0..*" PropertyValue
SingleOption::objectTypeProperties --> "0..*" PropertyValue : "     "
SingleOption::relationshipTypeProperties --> "0..*" PropertyValue
FormatDefintion::baseFormat -right-> "[0..1]" SingleFormat
FormatDefintion::formats -down-> "[0..*]" NamedFormat
NamedFormat::definition -right-> "[0..1]" SingleFormat
CharacteristicProperty -[hidden]right-> CharacteristicPropertyType
CharacteristicPropertyType -[hidden]right-> ObjectProperty

@enduml
