@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class CurlParameter {
	name : String
	value : String
}

class GlobalConfiguration <<Pivot>>{
   additionalServiceInformation : String
   baseOutputPath : String
   outputPath : String
   curlAuthenticationFileName : String
   curlCommand : String
   curlParameter : Array of CurlParameter
   curlPassThroughHeader : Array of String
   curlSpanIdHeader : String
   curlTraceIdHeader : String
   curlUserAgentInformation : String
   defaultDefinitionFileName : String
   definitionFileSearchFolder : Array of String
   inputListFileSearchFolder : Array of String
   javaRuntimeParameter : String
   logFileOutputPath : String
   plantUmlJarFileName : String
   plantUmlRuntimeParameter : String
   servicePort : Integer
}

GlobalConfiguration::curlParameter --> "0..*" CurlParameter
@enduml
