@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class DefinitionFile{
   name : String
   displayName : String
   description : String
}
class DefinitionOption {
   option : String
   displayName : String
   description : String
}

class CurlParameter{
   name : String
   displayName : String
   description : String
   mandatory : Boolean
   mandatoryGroup : Boolean
   regularExpression : String
   defaultValue : String
}

class InputListFile {
   name : String
   displayName : String
   description : String
   definitionFile : DefinitionFile
   options : Array of DefinitionOption
   curlParameter : Array of CurlParameter
   curlAuthenticationParameter : Array of CurlParameter
}

class InputListFiles <<pivot>>{
   Array of InputListFile
}
InputListFiles -right-> "0..*" InputListFile
InputListFile::definitionFile --> "0..1" DefinitionFile
InputListFile::options --> "0..*" DefinitionOption
InputListFile::curlParameter -right-> "0..*" CurlParameter
InputListFile::curlAuthenticationParameter -right-> "0..*" CurlParameter

'CurlParameter -[hidden]up-> DefinitionFile
'CurlParameter <-[hidden]left- DefinitionFile


@enduml
