@startuml
hide circle
hide methods
hide stereotype
'skinparam linetype polyline
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class OutputFormat <<Enumeration>> {
    png
    svg
}

class InfoListDescription {
    displayName : String
    description : String
    curlParameter : Array of InfoListDescriptionCurlParameter
}

class InfoListDescriptionCurlParameter {
    name : String
    displayName : String
    description : String
    mandatory : Boolean
    regularExpression : String
}

class InfolistFile  <<Pivot>> {
  description : InfoListDescription
  --
  definitionFile : String
  --
  generateDetails : Boolean 
  generateSummary : Boolean
  --
  group : String
  detail : String
  job : string
  option : String
  --
  outputFormats : Array of OutputFormat 
  outputPath : String
  outputSuffix : String
  summaryFileName : String
  --
  curlBaseUrl : String
  curlUrlAddon : String 
  curlOptions : String
  --
  input : Array of SingleListFile
}

class singleListFileCurlOutputParameter {
    name : String
    value : String
    maxValues : Integer
}

class SingleListFile {
    inputFile : String
    leadingObject : String
    ---
	generateOutput : Boolean
    splitIdentifier : String
    splitInputFile : String
    ---
    curlBaseUrl : String
    curlUrl : String
	curlCache : Integer
    curlOptions: String
	curlOutputParameter : <AnyRecord>
}

InfolistFile::input --> SingleListFile::inputFile
InfolistFile::outputFormats -left-> OutputFormat
InfolistFile::description -right-> InfoListDescription::displayName
InfoListDescription::curlParameter -right-> InfoListDescriptionCurlParameter::name
SingleListFile::curlOutputParameter -right-> singleListFileCurlOutputParameter::name

@enduml
