@startuml
hide circle
hide methods
hide stereotype
'skinparam linetype polyline
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class OutputFormat <<Enumeration>> {
    png
    svg
}

class InputlistDescription {
    displayName : String
    description : String
    curlParameter : Array of InputlistDescriptionCurlParameter
    curlAuthenticationParameter : Array of InputlistDescriptionCurlParameter
}

class InputlistDescriptionCurlParameter {
    name : String
    displayName : String
    description : String
    mandatory : Boolean
    regularExpression : String
}

class InputlistFile  <<Pivot>> {
  description : InputlistDescription
  --
  definitionFile : String
  --
  generateDetails : Boolean 
  generateSummary : Boolean
  --
  group : String
  detail : String
  job : string
  jobDescription : String
  option : String
  --
  outputFormats : Array of OutputFormat 
  outputPath : String
  outputSuffix : String
  summaryFileName : String
  --
  curlBaseUrl : String
  curlUrlAddon : String 
  curlOptions : String
  --
  input : Array of SingleListFile
}

class curlOutputParameter {
    name : String
    value : String
    maxValues : Integer
}

class SingleListFile {
    inputFile : String
    leadingObject : String
    ---
	generateOutput : Boolean
    splitIdentifier : String
    splitInputFile : String
    ---
    curlBaseUrl : String
    curlUrl : String
    curlFileSuffix : String
    curlFormatOutput : Boolean
	curlCache : Integer
    curlOptions: String
	curlOutputParameter : Array of curlOutputParmater
}

InputlistFile::input --> SingleListFile::inputFile
InputlistFile::outputFormats -left-> OutputFormat
InputlistFile::description -up-> InputlistDescription
InputlistDescription::curlParameter -right-> InputlistDescriptionCurlParameter::name
InputlistDescription::curlAuthenticationParameter -right-> InputlistDescriptionCurlParameter::name
SingleListFile::curlOutputParameter -right-> curlOutputParameter::name

@enduml
