@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}


class CurlParameter {
	name : String
	value : String
}

class UrlConfiguration {
   baseUrl : String
   parameter : Array of CurlParameter
}

class UrlAuthentication <<pivot>> {
   Array of UrlConfiguration
}

UrlAuthentication --> "0..*" UrlConfiguration
UrlConfiguration::parameter -right-> "0..*" CurlParameter

@enduml
