openapi: '3.0.2'
info:
  title: json2puml API
  description: |-
    This is the api interface to an json2puml curl execcution server. 

    It could be used to execute a json2puml list definition file. 
    The results will be returned as a list of files.

  contact:
    email: jens.fudickar@oratool.de
  version: '1.1'
servers:
  - url: https://api.server.test/v1/api
paths:
  /heartbeat:
    get:
      description: 'Heartbeat function returning service version information'
      parameters: []
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: 
                'json2puml server v2.2.5.96 (Windows 64Bit)'
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
                
  /serviceinformation:
    get:
      description: 'Returns a set of informations about the service application and the current configuration'
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ServiceInformationResponse'
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
  /errormessages:
    get:
      description: 'Returns the list of all error messages defined in the system'
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
  /definitionfile:
    get:
      description: 'Returns a list of all available definition files'
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DefinitionFileResponse'
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
  /inputlistfile:
    get:
      description: 'Returns a list of all available input list files'
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InputListFileResponse'          
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
    
  /json2pumlRequest:
    post:
      description: 'Execute a json2puml curl and generation call'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Json2PumlRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Json2PumlResponse'        
        '400':
          description: '*Bad Request* - The server cannot process the request due to malformed\
            \ syntax. The response can be caused by missing mandatory query parameters,\
            \ invalid value in the query parameters, validation exceptions, and so on.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
  /json2pumlRequestPng:
    post:
      description: 'Execute a json2puml curl and generation call and returns the summary PNG file'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Json2PumlRequest'
      responses:
        '200':
          description: Successful operation, returns the generated PNG file
          content:
            image/png:
              schema: 
                type: string
                format: binary
        '400':
          description: '*Bad Request* - The server cannot process the request due to malformed\
            \ syntax. The response can be caused by missing mandatory query parameters,\
            \ invalid value in the query parameters, validation exceptions, and so on.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
  /json2pumlRequestSvg:
    post:
      description: 'Execute a json2puml curl and generation call and returns the summary SVG file'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Json2PumlRequest'
      responses:
        '200':
          description: Successful operation, returns the generated SVG file
          content:
            image/svg+xml:
              schema: 
                type: string
                format: binary
        '400':
          description: '*Bad Request* - The server cannot process the request due to malformed\
            \ syntax. The response can be caused by missing mandatory query parameters,\
            \ invalid value in the query parameters, validation exceptions, and so on.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
  /json2pumlRequestZip:
    post:
      description: 'Execute a json2puml curl and generation call and returns a zip file containing all generated filee'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Json2PumlRequest'
      responses:
        '200':
          description: Successful operation, returns the generated SVG file
          content:
            application/zip:
              schema: 
                type: string
                format: binary
        '400':
          description: '*Bad Request* - The server cannot process the request due to malformed\
            \ syntax. The response can be caused by missing mandatory query parameters,\
            \ invalid value in the query parameters, validation exceptions, and so on.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
        '500':
          description:  '*Internal Server Error* - The server encountered an unexpected condition\
            \ that prevented it from fulfilling the request.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'        
components:
  schemas:
    ServiceInformationResponse:
      type: object
      description: Various informations about the service and the configuration
      properties:
        service:
          type: string
          example: simplelistfile
          description: Name of the listfile which can be used in the POST /json2pumlRequest parameters
        additionalServiceInformation:
          type: array
          items:
            type : string
          description: Optional additional informations which can be configured in the global configuraion file
        plantUmlInformation:
          type: array
          items:
            type : string
          description: Output of the plantuml -version call of the configured plantuml jar file
        definitionFiles:
          type: array
          items:
            type : string
          description: List of all definition files configured for the system
        inoutlistFiles:
          type: array
          items:
            type : string
          description: List of all inputlist files configured for the system
    InputListFileResponse:
      type: object
      description: Definition of a input list file which will be returned by get /inputlistfile 
      properties:
        name:
          type: string
          example: son2puml v2.1.8.83 (Windows 64Bit x86 Debug)
          description: Name, version number and executable detail informations of the service application
        displayName:
          type: string
          example: Json Placeholder Input List File using Curl
          description: Optional display value which can be shown in a UI to make it better readable
        description:
          type: string
          example: This file contains a set of filedefinitions which are using curl to fetch the data from https://jsonplaceholder.typicode.com/
          description: Optional description of the of the input list file
        definitionFile:
          $ref: '#/components/schemas/DefinitionFileResponse'  
          description: Details of the definition file which is defined in the input list file. When the definition file is not defined in the input list file it must be implicitly defined in the POST /json2pumlRequest parameters
        curlParameter:
          type: array
          items:
            $ref: '#/components/schemas/InputListFileParameter' 
          description: List of parameters which can be defined when calling a curl based list file generation
    InputListFileParameter:
      type: object
      description: Parameter definition of the optional curl parameters which can be defined when handling the InputListFile
      properties:
        name:
          type: string
          description: Name of the curl parameter
          example: customer_number
        displayName: 
          type: string
          description: Optional display value which can be shown in a UI to make it better readable
          example: Customer Number
        description:
          type: string
          description: Optional description of the parameter
          example: The curstomer number to search for
        mandatory:
          type: boolean
          description: Flag to describe if the curl parameter is optional or mandatory
        regularExpression:
          type: string
          description: Optional regular expression which could be used by a UI to validate the curl parameters
          example: 10[0-9]{10}
        defaultValue:
          type: string
          description: Default value of the parameter
          example: 101234512345
      required:
        - name
    DefinitionFileResponse:
      type: object
      description: Definition of a converter definition file 
      properties:
        name:
          type: string
          example: jsonplaceholderdefinition.json
        displayName:
          type: string
          example: JsonPlaceHolder Definition File
        description:
          type: string
          example: Definition file to handle and convert JsonPlaceHolder based data files.
        options:
          type: array
          description: List of options defined by the definition file
          items:
            type : string
            example: 
            - full
            - default
            - core
    Json2PumlRequest:
      type: object
      properties:
        definitionFile:
          type: string
          example: placeholderdefinition.json
        inputFiles:
          type: array
          items:       
            type: object
            properties:
              fileName:
                type: string
                example: users.json
              leadingObject:
                type: string
                example: user
              content:
                type: object
                description: Json structure to be interpreted
            required:
              - fileName
              - leadingObject
              - content
        inputlistFile:
          type: string
          example: placeholderinputlistreduced.json
        curlParameter:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: ID
              value:
                type: string
                example: 1
        option: 
          type: string
          description: The option which should be used to generate the image. The possible options are defined in the definition file.
          example: full, default, core
        description: 
          type: string
          description: The description will be added to the legend of the generated images
          example: Datamodel status after migration of the customer
        generateDetails: 
          type: boolean
          description: Flag to define if for every single result file a image will be generated\nWill be ignored for json2pumlRequestSvg
        generateSummary: 
          type: boolean
          description: Flag to define if a summary file should be generated\nWill be ignored for json2pumlRequestSvg
        generateSuffix: 
          type: string
          description: Suffix to be added at the end of the generated files'
          example : .<option>
        outputFormats:
          type: array
          description: List of file formats to be calculated and added to the result set
          items:
            type: string
            enum:
              - svg
              - png
              - json
              - puml
              - zip
            example:
            - svg
            - png
    Json2PumlResponse:
      type: object
      properties:
        summaryfile:
          $ref: '#/components/schemas/GeneratedOutputFile'
        detailfiles:
          type: array
          items:
            $ref: '#/components/schemas/GeneratedOutputFile'
          
    OutputFile:
      type: object
      properties:
        outputFilename:
          type: string
        fullFilename:
          type: string
        content:  
          type: string
    GeneratedOutputFile:
      type: object
      properties:
        isSplitFile:
          type: boolean
        pumlFile:
          $ref: '#/components/schemas/OutputFile'
        pdfFile:
          $ref: '#/components/schemas/OutputFile'
        pngFile:
          $ref: '#/components/schemas/OutputFile'
        svgFile:
          $ref: '#/components/schemas/OutputFile'
        converterLogFile:
          $ref: '#/components/schemas/OutputFile'
    ErrorResponse:
      type: array
      items:       
        type: object
        properties:
          errorCode: 
            type : string
          errorClass: 
            type : string
          message: 
            type : string
          description: 
            type : string

    

        

  